name: devops workflow for demo project
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Check Maven Version
        run: mvn -v
      - name: Build with Maven
        run: mvn -B -U package
