name: Dockerize devops-demo application
on: push
jobs:
  build-container:
    name: Build Docker container image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          version: v0.7.0
      - name: Publish to Github Packages
        uses: docker/build-push-action@v3
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: latest, ${{ github.run_number }}
          labels: latest, ${{ github.run_number }}
